name: Test

on:
#  schedule:
#      - cron: '0,30 * * * *'
      
  workflow_dispatch:    
#  workflow_call:
    
jobs:
  collect_rx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: set identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install hamplots
        run: |
          python -m pip install --upgrade pip
          python -m pip install hamplots --upgrade 
          
      - name: start_rx
        run: hamplots start_rx --runsecs 10000
